"""Build the whole site: ``python3 site/build.py [--out DIR] [--dev] [--all-languages]``."""
from __future__ import annotations

import argparse
import base64
import hashlib
import io
import json
import os
import re
import shutil
import sys
import time
import zipfile
from pathlib import Path
from typing import Optional
from xml.sax.saxutils import quoteattr

from . import assets, discovery, layout
from .config import ANALYTICS_ENV, CONTENT_DIR, DEFAULT_OUT, I18N_DIR, LANGS, PUBLISHED, SITE_URL
from .context import Ctx, Route, Site
from .data import DERIVED_DIR, Hub, load as load_data
from .i18n import Catalog
from .pages import dev as dev_page, invitation, root
from .routes import ROUTES

MARKER = '.djsite-build'

ROOT_SCRIPT_HASH = base64.b64encode(hashlib.sha256(root.REDIRECT_JS.encode('utf-8')).digest()).decode('ascii')
CONTENT_POLICY = (f"script-src 'self' https://static.cloudflareinsights.com 'sha256-{ROOT_SCRIPT_HASH}'; "
                  "script-src-attr 'none'; base-uri 'self'; object-src 'none'; form-action 'self'")

HEADERS = f"""# Cloudflare response headers for the static assets (generated by site/build.py)
/*
  Cache-Control: public, max-age=0, must-revalidate
  Strict-Transport-Security: max-age=31536000
  Content-Security-Policy: {CONTENT_POLICY}; frame-ancestors 'self'
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: SAMEORIGIN
  Permissions-Policy: camera=(), microphone=(), geolocation=(), browsing-topics=()
/assets/*
  ! Cache-Control
  Cache-Control: public, max-age=31536000, immutable
/charts/*
  Access-Control-Allow-Origin: *
/data/*
  Access-Control-Allow-Origin: *
/en/embed/*
  ! X-Frame-Options
  ! Content-Security-Policy
  Content-Security-Policy: {CONTENT_POLICY}; frame-ancestors *
/ar/embed/*
  ! X-Frame-Options
  ! Content-Security-Policy
  Content-Security-Policy: {CONTENT_POLICY}; frame-ancestors *
/.well-known/security.txt
  Content-Type: text/plain; charset=utf-8
/security.txt
  Content-Type: text/plain; charset=utf-8
"""
MARKDOWN_HEADERS = """/{lang}/data/index.md
  Content-Type: text/markdown; charset=utf-8
"""


ROBOTS = f"""# robots.txt (generated by site/build.py)
User-agent: *
Allow: /

Sitemap: {SITE_URL}/sitemap.xml
"""


def lastmod(site: Site, key: str) -> Optional[str]:
    """The date a page's content last changed, where the build knows it: the quarter's release
    for the Index, the Hub's last sync, the release or the latest log entry for the Data page.
    Other pages have none, rather than a date that changes with every build."""
    release = site.data.release_date
    synced = site.hub.synced.date().isoformat() if site.hub and site.hub.synced else None
    route = site.routes[key]
    if route.section == 'index':
        return release
    if key == 'hub':
        return synced
    if key == 'home':
        return max(d for d in (release, synced) if d)
    if key == 'data':
        logged = [e['date'] for name in ('changelog.json', 'corrections.json')
                  for e in json.loads((CONTENT_DIR / name).read_text('utf-8'))['entries'] if e.get('date')]
        return max([release, *logged])
    return None


def sitemap(site: Site) -> str:
    """Every indexed page in each language, with its other versions (hreflang) and the date it
    last changed. ``/`` is listed only while it chooses between languages, as Home's x-default;
    with one language it redirects (``redirects``). Placeholders, 404 pages and invitations are left out."""
    def url(key, lang):
        return f'{SITE_URL}/{lang}/{site.routes[key].path}'

    entries = []
    for key, route in site.routes.items():
        langs = [lang for lang in LANGS if lang in site.published and lang in site.indexed.get(key, ())]
        root = key == 'home' and site.chooser
        x_default = f'{SITE_URL}/' if root else url(key, 'en')
        alts = [(lang, url(key, lang)) for lang in langs] + [('x-default', x_default)]
        locs = [url(key, lang) for lang in langs] + ([x_default] if root else [])
        date = lastmod(site, key)
        for loc in locs:
            links = ''.join(f'\n    <xhtml:link rel="alternate" hreflang="{lang}" href={quoteattr(href)}/>' for lang, href in alts)
            stamp = f'\n    <lastmod>{date}</lastmod>' if date else ''
            entries.append(f'  <url>\n    <loc>{loc}</loc>{stamp}{links}\n  </url>')
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
            + '\n'.join(entries) + '\n</urlset>\n')


def redirects(site: Site) -> str:
    """Cloudflare's _redirects, which apply before the static assets: ``/`` to the only published
    language, and ``/<lang>/index``, which Cloudflare would otherwise read as Home's
    ``index.html``, to the Index at ``/<lang>/index/``. Both permanent."""
    lines = ['# Cloudflare redirects (generated by site/build.py). They apply before the static assets.']
    if not site.chooser:
        lines.append(f'/ /{site.published[0]}/ 301')
    for lang in LANGS:
        for route in site.routes.values():
            if route.path.endswith('/') and route.path.rstrip('/').rsplit('/', 1)[-1] == 'index':
                lines.append(f'/{lang}/{route.path.rstrip("/")} /{lang}/{route.path} 301')
    return '\n'.join(lines) + '\n'


def _prepare(out: Path) -> None:
    """Empty the output folder, but only if an earlier build made it."""
    if out.exists():
        if any(out.iterdir()) and not (out / MARKER).exists():
            raise SystemExit(f'{out} exists and was not made by site/build.py; refusing to delete it')
        shutil.rmtree(out)
    out.mkdir(parents=True)
    (out / MARKER).write_text('Made by site/build.py. Safe to delete.\n')


def add_data_files(site: Site, derived_dir: Path) -> None:
    """Publish the derived data at /data/: every quarter folder, as the pipeline wrote it, and
    latest.json, which names the newest one. Table files are checked against their manifest."""
    for folder in sorted(p for p in Path(derived_dir).iterdir() if (p / 'manifest.json').is_file()):
        quarter = site.data if folder == site.data.folder else type(site.data)(folder)
        for name in sorted(quarter.files):
            site.add_file(f'/data/{folder.name}/{name}', quarter.read(name))
        for name in ('manifest.json', 'README.md'):
            if (folder / name).is_file():
                site.add_file(f'/data/{folder.name}/{name}', (folder / name).read_bytes())
        site.add_file(f'/data/{folder.name}/{quarter.zip_name}', csv_zip(quarter))
    site.add_file('/data/latest.json', (Path(derived_dir) / 'latest.json').read_bytes())


def csv_zip(quarter) -> bytes:
    """A quarter's CSV tables with its README and manifest, in one zip. Names, order and
    timestamps are fixed, so the same data always gives the same file."""
    stamp = tuple(int(x) for x in quarter.release_date.split('-')) + (0, 0, 0)
    names = sorted(n for n in quarter.files if n.endswith('.csv'))
    extra = [n for n in ('README.md', 'manifest.json') if (quarter.folder / n).is_file()]
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w') as z:
        for name in names + extra:
            data = quarter.read(name) if name in quarter.files else (quarter.folder / name).read_bytes()
            info = zipfile.ZipInfo(f'{quarter.folder.name}/{name}', date_time=stamp)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            z.writestr(info, data, compresslevel=9)
    return buf.getvalue()


def output_path(out: Path, lang: str, path: str) -> Path:
    dest = out / lang / path
    return dest / 'index.html' if path == '' or path.endswith('/') else dest


def analytics_token(value: Optional[str] = None) -> str:
    """The Cloudflare Web Analytics token: ``value``, or the environment variable. Checked, because
    it goes into every page."""
    token = (os.environ.get(ANALYTICS_ENV, '') if value is None else value).strip()
    if token and not re.fullmatch(r'[0-9a-f]{32}', token):
        raise SystemExit(f'{ANALYTICS_ENV} must be the 32 hexadecimal characters Cloudflare gives a site')
    return token


def build(out: Path = DEFAULT_OUT, dev: bool = False, routes=None, quiet: bool = False, i18n_dir: Path = I18N_DIR,
          derived_dir: Path = DERIVED_DIR, hub_dir: Optional[Path] = None, analytics: Optional[str] = None,
          published: tuple = PUBLISHED) -> Site:
    """``analytics``: the Cloudflare Web Analytics token; by default read from the environment.
    ``published``: the languages served in full; every address in another shows the invitation to
    translate (pages/invitation.py)."""
    started = time.time()
    catalog = Catalog(i18n_dir)
    all_routes = list(routes or ROUTES)
    if dev:
        all_routes.append(Route('dev-components', '_dev/components/', dev_page.render, indexed=False))
    site = Site(catalog=catalog, routes={r.key: r for r in all_routes}, dev=dev, data=load_data(derived_dir),
                hub=Hub(hub_dir or Path(derived_dir) / 'hub'), analytics=analytics_token(analytics),
                published=tuple(lang for lang in LANGS if lang in published))
    _prepare(out)
    site.assets = assets.build(out, release=site.data.folder.name, langs=site.published)
    add_data_files(site, derived_dir)

    for lang in site.published:
        for route in sorted(site.routes.values(), key=lambda r: r.last):
            ctx = Ctx(site, lang, route)
            page = route.render(ctx)
            if route.indexed and page.indexed:
                site.indexed.setdefault(route.key, set()).add(lang)
            dest = output_path(out, lang, route.path)
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(layout.document(ctx, page), 'utf-8')

    for path, data in sorted(site.files.items()):
        dest = out / path.lstrip('/')
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)

    # A language that isn't published: the invitation to translate at each of its addresses,
    # after the English pages, which register the chart embeds.
    for lang in (lang for lang in LANGS if lang not in site.published):
        for path, route, english in invitation.addresses(site):
            ctx = Ctx(site, lang, route, links=site.published[0])
            dest = output_path(out, lang, path)
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(layout.document(ctx, invitation.render(ctx, english)), 'utf-8')

    (out / 'index.html').write_text(root.render(site), 'utf-8')
    shutil.copy2(out / 'en' / '404.html', out / '404.html')
    (out / '_headers').write_text(HEADERS + ''.join(MARKDOWN_HEADERS.format(lang=lang) for lang in site.published), 'utf-8')
    (out / '_redirects').write_text(redirects(site), 'utf-8')
    # Files Cloudflare doesn't upload: the build's own marker stays off the site.
    (out / '.assetsignore').write_text(f'{MARKER}\n', 'utf-8')
    xml = sitemap(site)
    (out / 'sitemap.xml').write_text(xml, 'utf-8')
    (out / 'robots.txt').write_text(ROBOTS, 'utf-8')
    discovery.write(out, site, xml)

    if quiet:
        return site
    missing = catalog.missing('ar')
    stale = catalog.stale('ar')
    html = [p.relative_to(out).as_posix() for p in out.rglob('*.html')]
    embeds = sum(1 for p in html if '/embed/' in p)
    downloads = sum(1 for name in site.files if not name.endswith('.html'))
    print(f'Built {len(html) - embeds} pages, {embeds} chart embeds and {downloads} downloads into {out} '
          f'in {time.time() - started:.1f}s')
    if missing:
        print(f'  ar.json: {len(missing)} keys fall back to English: {", ".join(missing[:8])}{" …" if len(missing) > 8 else ""}')
    if stale:
        print(f'  ar.json: {len(stale)} keys no longer in en.json: {", ".join(stale[:8])}')
    return site


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out', type=Path, default=DEFAULT_OUT, help='output folder (default: site/dist)')
    parser.add_argument('--dev', action='store_true', help='also build the /_dev/ component pages')
    parser.add_argument('--all-languages', action='store_true',
                        help='build the pages of every language, published or not, to translate or review them (never deploy this)')
    args = parser.parse_args(argv)
    build(args.out.resolve(), dev=args.dev, published=LANGS if args.all_languages else PUBLISHED)
    return 0


if __name__ == '__main__':
    sys.exit(main())
