"""Build the whole site: ``python3 site/build.py [--out DIR] [--dev]``."""
from __future__ import annotations

import argparse
import io
import os
import re
import shutil
import sys
import time
import zipfile
from pathlib import Path
from typing import Optional
from xml.sax.saxutils import quoteattr

from . import assets, layout
from .config import ANALYTICS_ENV, DEFAULT_OUT, I18N_DIR, LANGS, SITE_URL
from .context import Ctx, Route, Site
from .data import DERIVED_DIR, Hub, load as load_data
from .i18n import Catalog
from .pages import dev as dev_page, home, root
from .routes import ROUTES

MARKER = '.djsite-build'

HEADERS = """# Cloudflare response headers for the static assets (generated by site/build.py)
/assets/*
  Cache-Control: public, max-age=31536000, immutable
/charts/*
  Access-Control-Allow-Origin: *
/data/*
  Access-Control-Allow-Origin: *
/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: SAMEORIGIN
  Permissions-Policy: camera=(), microphone=(), geolocation=(), browsing-topics=()
/en/embed/*
  ! X-Frame-Options
  Content-Security-Policy: frame-ancestors *
/ar/embed/*
  ! X-Frame-Options
  Content-Security-Policy: frame-ancestors *
"""


ROBOTS = f"""# robots.txt (generated by site/build.py)
User-agent: *
Allow: /

Sitemap: {SITE_URL}/sitemap.xml
"""


def sitemap(site: Site) -> str:
    """Every indexed page in each language, with its other versions (hreflang), and ``/``, the
    language chooser, which is the x-default for Home. Placeholders and 404 pages are left out."""
    def url(key, lang):
        return f'{SITE_URL}/{lang}/{site.routes[key].path}'

    entries = []
    for key, route in site.routes.items():
        langs = [lang for lang in LANGS if lang in site.indexed.get(key, ())]
        x_default = f'{SITE_URL}/' if key == 'home' else url(key, 'en')
        alts = [(lang, url(key, lang)) for lang in langs] + [('x-default', x_default)]
        locs = [url(key, lang) for lang in langs] + ([x_default] if key == 'home' else [])
        for loc in locs:
            links = ''.join(f'\n    <xhtml:link rel="alternate" hreflang="{lang}" href={quoteattr(href)}/>' for lang, href in alts)
            entries.append(f'  <url>\n    <loc>{loc}</loc>{links}\n  </url>')
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
            + '\n'.join(entries) + '\n</urlset>\n')


def _prepare(out: Path) -> None:
    """Empty the output folder, but only if an earlier build made it."""
    if out.exists():
        if any(out.iterdir()) and not (out / MARKER).exists():
            raise SystemExit(f'{out} exists and was not made by site/build.py; refusing to delete it')
        shutil.rmtree(out)
    out.mkdir(parents=True)
    (out / MARKER).write_text('Made by site/build.py. Safe to delete.\n')


def add_data_files(site: Site, derived_dir: Path) -> None:
    """Publish the derived data at /data/: every quarter folder, as the pipeline wrote it, and
    latest.json, which names the newest one. Table files are checked against their manifest."""
    for folder in sorted(p for p in Path(derived_dir).iterdir() if (p / 'manifest.json').is_file()):
        quarter = site.data if folder == site.data.folder else type(site.data)(folder)
        for name in sorted(quarter.files):
            site.add_file(f'/data/{folder.name}/{name}', quarter.read(name))
        for name in ('manifest.json', 'README.md'):
            if (folder / name).is_file():
                site.add_file(f'/data/{folder.name}/{name}', (folder / name).read_bytes())
        site.add_file(f'/data/{folder.name}/{quarter.zip_name}', csv_zip(quarter))
    site.add_file('/data/latest.json', (Path(derived_dir) / 'latest.json').read_bytes())


def csv_zip(quarter) -> bytes:
    """A quarter's CSV tables with its README and manifest, in one zip. Names, order and
    timestamps are fixed, so the same data always gives the same file."""
    stamp = tuple(int(x) for x in quarter.release_date.split('-')) + (0, 0, 0)
    names = sorted(n for n in quarter.files if n.endswith('.csv'))
    extra = [n for n in ('README.md', 'manifest.json') if (quarter.folder / n).is_file()]
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w') as z:
        for name in names + extra:
            data = quarter.read(name) if name in quarter.files else (quarter.folder / name).read_bytes()
            info = zipfile.ZipInfo(f'{quarter.folder.name}/{name}', date_time=stamp)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            z.writestr(info, data, compresslevel=9)
    return buf.getvalue()


def output_path(out: Path, lang: str, path: str) -> Path:
    dest = out / lang / path
    return dest / 'index.html' if path == '' or path.endswith('/') else dest


def analytics_token(value: Optional[str] = None) -> str:
    """The Cloudflare Web Analytics token: ``value``, or the environment variable. Checked, because
    it goes into every page."""
    token = (os.environ.get(ANALYTICS_ENV, '') if value is None else value).strip()
    if token and not re.fullmatch(r'[0-9a-f]{32}', token):
        raise SystemExit(f'{ANALYTICS_ENV} must be the 32 hexadecimal characters Cloudflare gives a site')
    return token


def build(out: Path = DEFAULT_OUT, dev: bool = False, routes=None, quiet: bool = False, i18n_dir: Path = I18N_DIR,
          derived_dir: Path = DERIVED_DIR, hub_dir: Optional[Path] = None, analytics: Optional[str] = None) -> Site:
    """``analytics``: the Cloudflare Web Analytics token; by default read from the environment."""
    started = time.time()
    catalog = Catalog(i18n_dir)
    all_routes = list(routes or ROUTES)
    if dev:
        all_routes.append(Route('dev-components', '_dev/components/', dev_page.render, indexed=False))
    site = Site(catalog=catalog, routes={r.key: r for r in all_routes}, dev=dev, data=load_data(derived_dir),
                hub=Hub(hub_dir or Path(derived_dir) / 'hub'), analytics=analytics_token(analytics))
    _prepare(out)
    site.assets = assets.build(out, extra_css=home.ticker_css(site.data), release=site.data.folder.name)
    add_data_files(site, derived_dir)

    for lang in LANGS:
        for route in sorted(site.routes.values(), key=lambda r: r.last):
            ctx = Ctx(site, lang, route)
            page = route.render(ctx)
            if route.indexed and page.indexed:
                site.indexed.setdefault(route.key, set()).add(lang)
            dest = output_path(out, lang, route.path)
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(layout.document(ctx, page), 'utf-8')

    for path, data in sorted(site.files.items()):
        dest = out / path.lstrip('/')
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)

    (out / 'index.html').write_text(root.render(site), 'utf-8')
    shutil.copy2(out / 'en' / '404.html', out / '404.html')
    (out / '_headers').write_text(HEADERS, 'utf-8')
    # Files Cloudflare doesn't upload: the build's own marker stays off the site.
    (out / '.assetsignore').write_text(f'{MARKER}\n', 'utf-8')
    (out / 'sitemap.xml').write_text(sitemap(site), 'utf-8')
    (out / 'robots.txt').write_text(ROBOTS, 'utf-8')

    if quiet:
        return site
    missing = catalog.missing('ar')
    stale = catalog.stale('ar')
    html = [p.relative_to(out).as_posix() for p in out.rglob('*.html')]
    embeds = sum(1 for p in html if '/embed/' in p)
    downloads = sum(1 for name in site.files if not name.endswith('.html'))
    print(f'Built {len(html) - embeds} pages, {embeds} chart embeds and {downloads} downloads into {out} '
          f'in {time.time() - started:.1f}s')
    if missing:
        print(f'  ar.json: {len(missing)} keys fall back to English: {", ".join(missing[:8])}{" …" if len(missing) > 8 else ""}')
    if stale:
        print(f'  ar.json: {len(stale)} keys no longer in en.json: {", ".join(stale[:8])}')
    return site


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out', type=Path, default=DEFAULT_OUT, help='output folder (default: site/dist)')
    parser.add_argument('--dev', action='store_true', help='also build the /_dev/ component pages')
    args = parser.parse_args(argv)
    build(args.out.resolve(), dev=args.dev)
    return 0


if __name__ == '__main__':
    sys.exit(main())
