"""Build the whole site: ``python3 site/build.py [--out DIR] [--dev]``."""
from __future__ import annotations

import argparse
import shutil
import sys
import time
from pathlib import Path

from . import assets, layout
from .config import DEFAULT_OUT, I18N_DIR, LANGS, SITE_DIR
from .context import Ctx, Route, Site
from .i18n import Catalog
from .pages import dev as dev_page, root
from .routes import ROUTES

MARKER = '.djsite-build'

HEADERS = """# Cloudflare Pages response headers (generated by site/build.py)
/assets/*
  Cache-Control: public, max-age=31536000, immutable
/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: SAMEORIGIN
  Permissions-Policy: camera=(), microphone=(), geolocation=(), browsing-topics=()
"""


def _prepare(out: Path) -> None:
    """Empty the output folder, but only if an earlier build made it."""
    if out.exists():
        if any(out.iterdir()) and not (out / MARKER).exists():
            raise SystemExit(f'{out} exists and was not made by site/build.py; refusing to delete it')
        shutil.rmtree(out)
    out.mkdir(parents=True)
    (out / MARKER).write_text('Made by site/build.py. Safe to delete.\n')


def output_path(out: Path, lang: str, path: str) -> Path:
    dest = out / lang / path
    return dest / 'index.html' if path == '' or path.endswith('/') else dest


def build(out: Path = DEFAULT_OUT, dev: bool = False, routes=None, quiet: bool = False) -> Site:
    started = time.time()
    catalog = Catalog(I18N_DIR)
    all_routes = list(routes or ROUTES)
    if dev:
        all_routes.append(Route('dev-components', '_dev/components/', dev_page.render, indexed=False))
    site = Site(catalog=catalog, routes={r.key: r for r in all_routes}, dev=dev)
    _prepare(out)
    site.assets = assets.build(out)
    if dev:
        (out / '_dev').mkdir()
        shutil.copy2(SITE_DIR / 'dev' / 'sample.json', out / '_dev' / 'sample.json')

    for lang in LANGS:
        for route in site.routes.values():
            ctx = Ctx(site, lang, route)
            page = route.render(ctx)
            dest = output_path(out, lang, route.path)
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(layout.document(ctx, page), 'utf-8')

    (out / 'index.html').write_text(root.render(site), 'utf-8')
    shutil.copy2(out / 'en' / '404.html', out / '404.html')
    (out / '_headers').write_text(HEADERS, 'utf-8')

    if quiet:
        return site
    missing = catalog.missing('ar')
    stale = catalog.stale('ar')
    pages = len(list(out.rglob('*.html')))
    print(f'Built {pages} pages into {out} in {time.time() - started:.1f}s')
    if missing:
        print(f'  ar.json: {len(missing)} keys fall back to English: {", ".join(missing[:8])}{" …" if len(missing) > 8 else ""}')
    if stale:
        print(f'  ar.json: {len(stale)} keys no longer in en.json: {", ".join(stale[:8])}')
    return site


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out', type=Path, default=DEFAULT_OUT, help='output folder (default: site/dist)')
    parser.add_argument('--dev', action='store_true', help='also build the /_dev/ component pages')
    args = parser.parse_args(argv)
    build(args.out.resolve(), dev=args.dev)
    return 0


if __name__ == '__main__':
    sys.exit(main())
