#!/usr/bin/env python3
"""Download the self-hosted fonts from Google Fonts (both SIL Open Font Licence 1.1).

Writes the woff2 subsets the site uses to ``site/static/fonts/``, their licences next
to them, and the matching ``@font-face`` rules to ``site/static/css/05-fonts.css``.
Run it only to update the fonts; the files are committed, so builds never need the network.

- Tajawal 400, 500, 700, 800: Arabic and Latin subsets.
- JetBrains Mono 400–700 (variable): Latin subset, which includes the minus sign and arrows.
"""
from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

SITE = Path(__file__).resolve().parent.parent
FONTS = SITE / 'static' / 'fonts'
CSS_OUT = SITE / 'static' / 'css' / '05-fonts.css'

API = ('https://fonts.googleapis.com/css2?family=Tajawal:wght@400;500;700;800'
       '&family=JetBrains+Mono:wght@400..700&display=swap')
# Google Fonts serves woff2 subsets only to browsers that say they support them.
UA = ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36')
LICENCES = {
    'OFL-Tajawal.txt': 'https://raw.githubusercontent.com/google/fonts/main/ofl/tajawal/OFL.txt',
    'OFL-JetBrainsMono.txt': 'https://raw.githubusercontent.com/google/fonts/main/ofl/jetbrainsmono/OFL.txt',
}
KEEP = {'Tajawal': {'arabic', 'latin'}, 'JetBrains Mono': {'latin'}}

BLOCK = re.compile(r'/\* (?P<subset>[\w-]+) \*/\s*@font-face \{(?P<body>[^}]*)\}')


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def field(body: str, name: str) -> str:
    return re.search(rf'{name}:\s*([^;]+);', body).group(1).strip()


def main() -> int:
    FONTS.mkdir(parents=True, exist_ok=True)
    css = get(API).decode('utf-8')
    rules = ['/* Self-hosted fonts (SIL Open Font Licence 1.1; licences in /assets/fonts/).',
             '   Generated by site/tools/fetch_fonts.py: edit that script, not this file. */']
    for m in BLOCK.finditer(css):
        subset, body = m.group('subset'), m.group('body')
        family = field(body, 'font-family').strip("'")
        if subset not in KEEP.get(family, ()):
            continue
        weight = field(body, 'font-weight')
        url = re.search(r'url\((https://[^)]+\.woff2)\)', body).group(1)
        slug = family.lower().replace(' ', '-')
        name = f'{slug}-{subset}.woff2' if ' ' in weight else f'{slug}-{subset}-{weight}.woff2'
        data = get(url)
        (FONTS / name).write_bytes(data)
        print(f'{name}: {len(data) / 1024:.1f} KB')
        rules.append(f"@font-face {{ font-family: '{family}'; font-style: normal; font-weight: {weight}; "
                     f"font-display: swap; src: url(/assets/fonts/{name}) format('woff2'); "
                     f"unicode-range: {field(body, 'unicode-range')}; }}")
    for name, url in LICENCES.items():
        (FONTS / name).write_bytes(get(url))
        print(f'{name}: licence')
    CSS_OUT.write_text('\n'.join(rules) + '\n', 'utf-8')
    print(f'wrote {CSS_OUT.relative_to(SITE.parent)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
